[package]
name = "adder"
version = "0.1.0"
authors = ["gutrse3321 <gutrse3321@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
add-lib = {path = "../add-lib"} # 让 adder 依赖库 crate add-lib
